# pytorch_lightning==1.7.7
model:
  contrastive:
    enabled: True
  sup_only_epoch: 2
  unsupervised_apply_aug: "cutmix"
data:
  batch_size_val: 2
  train_h: 433
  train_w: 433
  semisupervised: True